#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "AEYNK/MazOYo"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

